[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
resolver = "2"
members = ["dnas/*/zomes/integrity/*", "dnas/*/zomes/coordinator/*"]

[workspace.dependencies]
hdi = "0.5.1"
hdk = "0.4.1"

serde = "1.0.193"

